# Usar la imagen base oficial de Python
FROM python:3.10.12

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el archivo de requisitos
COPY requirements.txt requirements.txt

# Instalar las dependencias necesarias
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    apt-transport-https \
    unixodbc \
    unixodbc-dev \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copiar el contenido del directorio actual al directorio de trabajo en el contenedor
COPY . .

# Exponer el puerto que usará la aplicación
EXPOSE 8084

# Comando para ejecutar la aplicación
CMD ["waitress-serve", "--host=0.0.0.0", "--port=8084", "app:app"]